name: Lint, Build and Deploy

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - test
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  lint_and_build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
#  deploy_production:
#    name: Deploy Production
#    runs-on: ubuntu-latest
#    needs: lint_and_build
#    if: github.ref == 'refs/heads/main'
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18
#          cache: 'yarn'
#      - name: Install dependencies
#        run: yarn install --frozen-lockfile
#      - name: Deploy
#        run: curl --location --request POST '${{ secrets.DEPLOY_PRODUCTION_URL }}'
      - name: Update the version
        id: update_version
        run: |
          echo "version=$(npm version ${{ github.event.inputs.version }} --no-git -tag-version)" >> $GITHUB_OUTPUT
      - name: Update Changelog
        id: update_changelog
        run: |
          sed -i 's/Unreleased/${{ steps.update_version.outputs.version }}/g' CHANGELOG.md
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.update_version.outputs.version }}
          title: "Release: ${{ steps.update_version.outputs.version }} Pull Request"
          body: "This pull request contains the updated package.json with the new release version"
          base: main
