name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ steps.update_version.outputs.version }}
          title: "Release: replace the oldest version: ${{ steps.update_version.outputs.version }}"
          body: "This pull request will update the version in the main repository"
          base: main
