name: Create pull request to bump version

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Bump version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: ${{ github.event.inputs.version }}
          skip-tag: true
          skip-push: true
          commit-message: 'CI: bumps version to {{version}}'

      - name: Get new version
        uses: beaconbrigade/package-json-version@v0.3
        with:
          path: .

      - name: Print the version
        run: echo "The version was ${{ steps.get-version.outputs.version }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Release
          title: 'Release: ${{ steps.get-version.outputs.version }}'
          body: Draft a new release from Main branch
          base: main
          branch: 'release/${{ steps.get-version.outputs.version }}'
          delete-branch: true


