name: Tag and create release

on:
  pull_request:
    types:
      - closed

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release:')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Get new version
      run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

    - name: Create release
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "v${{ secrets.GITHUB_TOKEN }}"
        tag_exists_error: false
        message: Release version ${{ secrets.GITHUB_TOKEN }}